---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-provisioner-0
spec:
  capacity:
    storage: {{disk_size}}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{hostpath}}
  claimRef:
    namespace: nfs-server-provisioner
    name: {{claimref_name}}